import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TabBar from "@/components/TabBar";
import SessionLayout from "@/components/RootLayout";
import "./globals.css";
import TopAppBar from "@/components/TopAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid grid-rows-[1fr_85%_1fr] h-screen overflow-y-hidden`}
      >
        {/* <SessionLayout> */}
          <div>
            <TopAppBar />
          </div>
          <div className="overflow-y-scroll">{children}</div>
          <div>
            <TabBar />
          </div>
        {/* </SessionLayout> */}
      </body>
    </html>
  );
}
