import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TabBar from "@/components/TabBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        <div>
          <TabBar />
        </div>
      </body>
    </html>
  );
}
